# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20fe1ace74790318950f2b91d828c89fc8b4db83b12b84f14e376b3ea3e2f546c472d1a192971500e267af22d090354232a187802b0cd722b19c328560fd7143

test:
  secret_key_base: 0494f4dfa0690d6faecf4a0636354365c33a2e321b6071b98a94de0202cd921f851c9944f502f8f1ff18d660a1aadefe6d9fa4d0041a8d8ef8468c185780e77f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
